import json
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CARDS_DIR = ROOT / "output" / "cards"
REPORT_DIR = ROOT / "output" / "reports"


def fmt_odds(value):
    if value in [None, "", "None"]:
        return "N/A"

    try:
        value = int(float(value))
        return f"+{value}" if value > 0 else str(value)
    except Exception:
        return str(value)


def fmt_pct(value):
    if value in [None, "", "None"]:
        return "N/A"

    try:
        return f"{float(value):.1f}%"
    except Exception:
        return str(value)


def load_json(path):
    path = Path(path)

    if not path.exists():
        return None

    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def recommendation_rank(game):
    model = game.get("model", {})
    edge = model.get("edge") or 0
    confidence = model.get("confidence") or 0
    return (edge * 2) + confidence


def get_best_picks(card, limit=8):
    if not card:
        return []

    games = card.get("games", [])

    picks = []

    for game in games:
        model = game.get("model", {})
        rec = model.get("recommendation") or ""

        if rec == "PASS":
            continue

        picks.append(game)

    return sorted(picks, key=recommendation_rank, reverse=True)[:limit]


def render_pick(game):
    model = game.get("model", {})
    odds = game.get("odds", {})
    matchup = game.get("matchup", {})

    pick = model.get("play")
    market = model.get("market") or "Moneyline"
    rec = model.get("recommendation") or "PLAY"
    edge = model.get("edge") or 0
    confidence = model.get("confidence") or 0
    price = odds.get("moneyline") or odds.get("american_odds")

    game_label = f"{matchup.get('away')} @ {matchup.get('home')}"

    lines = [
        f"**{rec}**",
        f"**{pick} {market}** ({fmt_odds(price)})",
        f"{game_label}",
        f"Edge: **{edge:.1f}** | Confidence: **{confidence:.1f}**",
    ]

    reasons = model.get("reasons", [])[:2]

    for reason in reasons:
        lines.append(f"• {reason}")

    return "\n".join(lines)


def render_bomb_lab(card, limit=8):
    if not card:
        return ""

    pitchers = card.get("pitchers", [])[:limit]

    if not pitchers:
        return ""

    lines = []
    lines.append("## 💣 Bomb Lab — HR Attack Board")

    for p in pitchers:
        score = p.get("bomb_score")
        tier = p.get("tier")
        pitcher = p.get("pitcher")
        game = p.get("game")
        side = p.get("target_side")
        confidence = p.get("sample_confidence")
        risk = p.get("pitcher_risk")

        lines.append("")
        lines.append(f"**{tier} — {pitcher}**")
        lines.append(f"{game}")
        lines.append(f"Attack Side: **{side}**")
        lines.append(f"Bomb Score: **{score}** | Risk: **{risk}** | Confidence: **{confidence}**")

        why = p.get("why", [])[:2]

        for reason in why:
            lines.append(f"• {reason}")

    return "\n".join(lines)


def build_discord_report():
    today = datetime.now().strftime("%Y-%m-%d")

    kbo = load_json(CARDS_DIR / "kbo_card.json")
    mlb = load_json(CARDS_DIR / "mlb_card.json")
    bomb = load_json(CARDS_DIR / "bomb_lab_card.json")

    lines = []
    lines.append(f"# SharpStack Daily Card — {today}")
    lines.append("")
    lines.append("## ⚾ Best Model Picks")

    all_picks = []

    for card in [mlb, kbo]:
        if not card:
            continue

        sport = card.get("sport", "SPORT")
        for game in get_best_picks(card, limit=8):
            all_picks.append((sport, game))

    all_picks = sorted(
        all_picks,
        key=lambda x: recommendation_rank(x[1]),
        reverse=True,
    )

    if not all_picks:
        lines.append("No model plays today.")
    else:
        for sport, game in all_picks[:10]:
            lines.append("")
            lines.append(f"### {sport}")
            lines.append(render_pick(game))

    bomb_text = render_bomb_lab(bomb, limit=10)

    if bomb_text:
        lines.append("")
        lines.append(bomb_text)

    lines.append("")
    lines.append("---")
    lines.append("_Generated by SharpStack. Bet responsibly._")

    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    output = REPORT_DIR / f"discord_report_{today}.md"

    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    latest = REPORT_DIR / "discord_report_latest.md"

    with open(latest, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return output, latest, "\n".join(lines)