"""create recommendation history schema

Revision ID: 3c0aa7bcc925
Revises: 
Create Date: 2026-07-18 15:47:29.695446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c0aa7bcc925'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues'))
    )
    op.create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=True)
    op.create_index(op.f('ix_leagues_sport'), 'leagues', ['sport'], unique=False)
    op.create_table('model_versions',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_name', 'version', 'git_commit', name='uq_model_versions_identity')
    )
    op.create_index(op.f('ix_model_versions_git_commit'), 'model_versions', ['git_commit'], unique=False)
    op.create_index(op.f('ix_model_versions_model_name'), 'model_versions', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=False)
    op.create_table('teams',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('external_team_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_teams_league_id_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('league_id', 'code', name='uq_teams_league_code')
    )
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=False)
    op.create_index(op.f('ix_teams_external_team_id'), 'teams', ['external_team_id'], unique=False)
    op.create_index(op.f('ix_teams_league_id'), 'teams', ['league_id'], unique=False)
    op.create_table('games',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('external_game_id', sa.String(length=150), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=False),
    sa.Column('away_team_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='scheduled', nullable=False),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_games_different_teams')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_games_away_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_games_home_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_games_league_id_leagues'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('league_id', 'external_game_id', name='uq_games_league_external_game')
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_external_game_id'), 'games', ['external_game_id'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_league_id'), 'games', ['league_id'], unique=False)
    op.create_index('ix_games_league_start_time', 'games', ['league_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_games_scheduled_start'), 'games', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=50), nullable=False),
    sa.Column('market_line', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('projection', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('edge', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), server_default='sharpstack', nullable=False),
    sa.Column('recommendation_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_recommendations_confidence_range')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_recommendations_game_id_games'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_recommendations_model_version_id_model_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index('ix_recommendations_game_created', 'recommendations', ['game_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_game_id'), 'recommendations', ['game_id'], unique=False)
    op.create_index('ix_recommendations_market_created', 'recommendations', ['market_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_market_type'), 'recommendations', ['market_type'], unique=False)
    op.create_index('ix_recommendations_model_created', 'recommendations', ['model_version_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_model_version_id'), 'recommendations', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_time'), 'recommendations', ['recommendation_time'], unique=False)
    op.create_index(op.f('ix_recommendations_selection'), 'recommendations', ['selection'], unique=False)
    op.create_index(op.f('ix_recommendations_source'), 'recommendations', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_source'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_selection'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_time'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_model_version_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_model_created', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_market_type'), table_name='recommendations')
    op.drop_index('ix_recommendations_market_created', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_game_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_game_created', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_scheduled_start'), table_name='games')
    op.drop_index('ix_games_league_start_time', table_name='games')
    op.drop_index(op.f('ix_games_league_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_external_game_id'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_league_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_external_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_name'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_git_commit'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_leagues_sport'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_code'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
