"""add model runs

Revision ID: 5d535e524d31
Revises: 3c0aa7bcc925
Create Date: 2026-07-18 20:13:44.393347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d535e524d31'
down_revision: Union[str, Sequence[str], None] = '3c0aa7bcc925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='running', nullable=False),
    sa.Column('source', sa.String(length=100), server_default='sharpstack', nullable=False),
    sa.Column('run_label', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_model_runs_completed_after_started')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_model_runs_model_version_id_model_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    op.create_index('ix_model_runs_model_started', 'model_runs', ['model_version_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_model_runs_model_version_id'), 'model_runs', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_model_runs_source'), 'model_runs', ['source'], unique=False)
    op.create_index(op.f('ix_model_runs_started_at'), 'model_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_model_runs_status'), 'model_runs', ['status'], unique=False)
    op.create_index('ix_model_runs_status_started', 'model_runs', ['status', 'started_at'], unique=False)
    op.add_column('recommendations', sa.Column('model_run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_recommendations_model_run_id'), 'recommendations', ['model_run_id'], unique=False)
    op.create_index('ix_recommendations_run_created', 'recommendations', ['model_run_id', 'created_at'], unique=False)
    op.create_foreign_key(op.f('fk_recommendations_model_run_id_model_runs'), 'recommendations', 'model_runs', ['model_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_recommendations_model_run_id_model_runs'), 'recommendations', type_='foreignkey')
    op.drop_index('ix_recommendations_run_created', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_model_run_id'), table_name='recommendations')
    op.drop_column('recommendations', 'model_run_id')
    op.drop_index('ix_model_runs_status_started', table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_status'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_started_at'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_source'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_model_version_id'), table_name='model_runs')
    op.drop_index('ix_model_runs_model_started', table_name='model_runs')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
