PARK_FACTORS = {
    "Arizona Diamondbacks": 1.02,
    "Atlanta Braves": 1.05,
    "Baltimore Orioles": 1.00,
    "Boston Red Sox": 1.08,
    "Chicago Cubs": 1.01,
    "Chicago White Sox": 1.08,
    "Cincinnati Reds": 1.15,
    "Cleveland Guardians": 0.98,
    "Colorado Rockies": 1.25,
    "Detroit Tigers": 0.94,
    "Houston Astros": 0.99,
    "Kansas City Royals": 1.00,
    "Los Angeles Angels": 1.00,
    "Los Angeles Dodgers": 1.02,
    "Miami Marlins": 0.93,
    "Milwaukee Brewers": 1.03,
    "Minnesota Twins": 1.01,
    "New York Mets": 0.97,
    "New York Yankees": 1.10,
    "Athletics": 0.90,
    "Philadelphia Phillies": 1.06,
    "Pittsburgh Pirates": 0.95,
    "San Diego Padres": 0.97,
    "San Francisco Giants": 0.92,
    "Seattle Mariners": 0.95,
    "St. Louis Cardinals": 0.98,
    "Tampa Bay Rays": 0.97,
    "Texas Rangers": 1.05,
    "Toronto Blue Jays": 1.07,
    "Washington Nationals": 1.01,
}